exports.seed = async function (knex) {
  const exists = await knex('products').first()

  if (exists) return

  await knex('products').insert([
    {
      name: 'V-Neck T-Shirt',
      description: 'Embroidered Seersucker Shirt',
      price: 99,
      image: '/images/Rectangle 18.png',
      category: 'men',
      is_new: false,
      size: 'L, XL, 2X',
      color: 'gray, white',
      in_stock: true,
      tags: 't-shirt, best-sellers',
      rating: 3,
    },
      {
      name: 'Cotton T-Shirt',
      description: 'Basic Slim Fit T-shirt',
      price: 99,
      image: '/images/Rectangle 15 (2).png',
      category: 'men',
      is_new: false,
      size: 'L, XL, 2X',
      color: 'white, black, gray',
      in_stock: true,
      tags: 't-shirt, best-seller',
      rating: 3,
    },
    {
      name: 'Cotton T-Shirt',
      description: 'Basic Slim T-shirt',
      price: 199,
      image: '/images/Rectangle 17.png',
      category: 'men',
      is_new: false,
      size: 'M, L, XL, 2X',
      color: 'white, black',
      in_stock: true,
      tags: 't-shirt, best-seller',
      rating: 4,
    },
    {
      name: 'Henley T-Shirt',
      description: 'Blurred print T-Shirt',
      price: 120,
      image: '/images/Rectangle 19.png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'gray, white',
      in_stock: true,
      tags: 't-shirt',
      rating: 3,
    },
    {
      name: 'Crewneck T-Shirt ',
      description: 'Full Sleeve Zipper',
      price: 250,
      image: '/images/Rectangle 20.png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'white, black, gray',
      in_stock: true,
      tags: 't-shirt',
      rating: 1,
    },
    {
      name: 'Cotton Jeans',
      description: 'Soft Wash Straight Fit Jeans',
      price: 300,
      image: '/images/Rectangle 12.png',
      category: 'men',
      is_new: false,
      size: 'XL, 2X',
      color: 'gray, white, black',
      in_stock: true,
      tags: 'jeans, best-seller',
      rating: 4,
    },
    {
      name: 'Black Suite',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (7).png',
      category: 'men',
      is_new: true,
      size: 'L, XL, 2X',
      color: 'black, gray',
      in_stock: true,
      tags: 'suit, new',
      rating: 2,
    },
    {
      name: 'Cotton Suite',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (8).png',
      category: 'men',
      is_new: true,
      size: 'M, L, XL, 2X',
      color: 'black, gray, red, blue, gold',
      in_stock: true,
      tags: 'suit, new, best-seller, coat',
      rating: 5,
    },
     {
      name: 'Red Shirt',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (9).png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'red, blue, black, white',
      in_stock: true,
      tags: 'shirt',
      rating: 1,
    },
     {
      name: 'Cotton Shirt',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (10).png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'gray, black, white',
      in_stock: true,
      tags: 'shirt, best-seller, polo-shirt',
      rating: 3,
    },
     {
      name: 'blue Shirt',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (11).png',
      category: 'men',
      is_new: true,
      size: 'S, M, L, XL',
      color: 'blue, gray, white, black, red',
      in_stock: true,
      tags: 'new, shirt',
      rating: 3,
    },
     {
      name: 'Sari Dark-Blue',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (12).png',
      category: 'women',
      is_new: false,
      size: 'XS, S, M, L',
      color: 'blue, red, black',
      in_stock: true,
      tags: 'best-seller',
      rating: 3,
    },
     {
      name: 'Gold Dress',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (13).png',
      category: 'women',
      is_new: true,
      size: 'XL, 2X',
      color: 'gold, white, black, red',
      in_stock: true,
      tags: 'new, best-seller',
      rating: 5,
    },
     {
      name: 'Red Sari',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (14).png',
      category: 'women',
      is_new: false,
      size: 'XS, S, M, L, XL, 2X',
      color: 'red, blue',
      in_stock: true,
      tags: 'new, best-seller',
      rating: 4,
    },
     {
      name: 'White Kid Shirt',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (1).png',
      category: 'kids',
      is_new: true,
      size: 'XS, S',
      color: 'white, black, gray, red, blue',
      in_stock: true,
      tags: 'new, shirt, best-seller',
      rating: 5,
    },
     {
      name: 'Cotton Blue',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (2).png',
      category: 'kids',
      is_new: false,
      size: 'XS',
      color: 'blue, black, red,',
      in_stock: true,
      tags: 'best-seller',
      rating: 4,
    },
     {
      name: 'Chines Full Dress',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (3).png',
      category: 'kids',
      is_new: true,
      size: 'XS, S',
      color: 'white, blue',
      in_stock: true,
      tags: 'new, jacket',
      rating: 4,
    },
     {
      name: 'Old Style Dress',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (4).png',
      category: 'kids',
      is_new: false,
      size: 'XS',
      color: 'blue, black, red, white',
      in_stock: true,
      tags: 'jacket',
      rating: 1,
    },
     {
      name: 'Zombie Style',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (5).png',
      category: 'kids',
      is_new: false,
      size: 'XS, S, M',
      color: 'red, white',
      in_stock: false,
      tags: 'short',
      rating: 0,
    },
     {
      name: 'Tiger Style',
      description: 'Basic Heavy Weight T-Shirt blue',
      price: 350,
      image: '/images/pngegg (6).png',
      category: 'kids',
      is_new: false,
      size: 'S',
      color: 'white, red, gray',
      in_stock: true,
      tags: 'jacket, best-seller',
      rating: 4,
    },
  ])
}