exports.seed = async function (knex) {
  // --- Check if products already exist ---
  const exists = await knex('products').first();

  // --- Skip seeding if products already exist ---
  if (exists) return;

  // --- Insert product data ---
  await knex('products').insert([
    {
      name: 'V-Neck T-Shirt',
      description: 'Soft V-neck tee, clean everyday fit.',
      price: 24,
      image: '/images/Rectangle 18.png',
      category: 'men',
      is_new: false,
      size: 'L, XL, 2X',
      color: 'gray, white',
      in_stock: true,
      tags: 't-shirt, best-sellers',
      rating: 3,
    },
    {
      name: 'Cotton T-Shirt',
      description: 'Slim cotton tee with durable stitching.',
      price: 19,
      image: '/images/Rectangle 15 (2).png',
      category: 'men',
      is_new: false,
      size: 'L, XL, 2X',
      color: 'white, black, gray',
      in_stock: true,
      tags: 't-shirt, best-seller',
      rating: 3,
    },
    {
      name: 'Cotton T-Shirt',
      description: 'Premium heavyweight tee that holds shape.',
      price: 29,
      image: '/images/Rectangle 17.png',
      category: 'men',
      is_new: false,
      size: 'M, L, XL, 2X',
      color: 'white, black',
      in_stock: true,
      tags: 't-shirt, best-seller',
      rating: 4,
    },
    {
      name: 'Henley T-Shirt',
      description: 'Classic Henley, breathable fabric, easy layering.',
      price: 32,
      image: '/images/Rectangle 19.png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'gray, white',
      in_stock: true,
      tags: 't-shirt',
      rating: 3,
    },
    {
      name: 'Crewneck T-Shirt ',
      description: 'Long-sleeve crewneck tee for cooler days.',
      price: 38,
      image: '/images/Rectangle 20.png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'white, black, gray',
      in_stock: true,
      tags: 't-shirt',
      rating: 1,
    },
    {
      name: 'Cotton Jeans',
      description: 'Soft-wash straight jeans with all-day comfort.',
      price: 54,
      image: '/images/Rectangle 12.png',
      category: 'men',
      is_new: false,
      size: 'XL, 2X',
      color: 'gray, white, black',
      in_stock: true,
      tags: 'jeans, best-seller',
      rating: 4,
    },
    {
      name: 'Black Suite',
      description: 'Modern black suit for formal occasions.',
      price: 189,
      image: '/images/pngegg (7).png',
      category: 'men',
      is_new: true,
      size: 'L, XL, 2X',
      color: 'black, gray',
      in_stock: true,
      tags: 'suit, new',
      rating: 2,
    },
    {
      name: 'Cotton Suite',
      description: 'Light cotton-blend suit, comfortable all day.',
      price: 159,
      image: '/images/pngegg (8).png',
      category: 'men',
      is_new: true,
      size: 'M, L, XL, 2X',
      color: 'black, gray, red, blue, gold',
      in_stock: true,
      tags: 'suit, new, best-seller, coat',
      rating: 5,
    },
    {
      name: 'Red Shirt',
      description: 'Bold red shirt with crisp collar.',
      price: 42,
      image: '/images/pngegg (9).png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'red, blue, black, white',
      in_stock: true,
      tags: 'shirt',
      rating: 1,
    },
    {
      name: 'Cotton Shirt',
      description: 'Breathable cotton shirt, relaxed regular fit.',
      price: 39,
      image: '/images/pngegg (10).png',
      category: 'men',
      is_new: false,
      size: 'S, M, L, XL, 2X',
      color: 'gray, black, white',
      in_stock: true,
      tags: 'shirt, best-seller, polo-shirt',
      rating: 3,
    },
    {
      name: 'blue Shirt',
      description: 'Fresh blue shirt with soft finish.',
      price: 41,
      image: '/images/pngegg (11).png',
      category: 'men',
      is_new: true,
      size: 'S, M, L, XL',
      color: 'blue, gray, white, black, red',
      in_stock: true,
      tags: 'new, shirt',
      rating: 3,
    },
    {
      name: 'Sari Dark-Blue',
      description: 'Elegant dark-blue sari with smooth drape.',
      price: 129,
      image: '/images/pngegg (12).png',
      category: 'women',
      is_new: false,
      size: 'XS, S, M, L',
      color: 'blue, red, black',
      in_stock: true,
      tags: 'best-seller',
      rating: 3,
    },
    {
      name: 'Gold Dress',
      description: 'Glam gold dress for special nights.',
      price: 149,
      image: '/images/pngegg (13).png',
      category: 'women',
      is_new: true,
      size: 'XL, 2X',
      color: 'gold, white, black, red',
      in_stock: true,
      tags: 'new, best-seller',
      rating: 5,
    },
    {
      name: 'Red Sari',
      description: 'Vibrant red sari, lightweight and graceful.',
      price: 119,
      image: '/images/pngegg (14).png',
      category: 'women',
      is_new: false,
      size: 'XS, S, M, L, XL, 2X',
      color: 'red, blue',
      in_stock: true,
      tags: 'new, best-seller',
      rating: 4,
    },
    {
      name: 'White Kid Shirt',
      description: 'Soft kids shirt for everyday play.',
      price: 18,
      image: '/images/pngegg (1).png',
      category: 'kids',
      is_new: true,
      size: 'XS, S',
      color: 'white, black, gray, red, blue',
      in_stock: true,
      tags: 'new, shirt, best-seller',
      rating: 5,
    },
    {
      name: 'Cotton Blue',
      description: 'Cozy blue cotton top, easy care.',
      price: 16,
      image: '/images/pngegg (2).png',
      category: 'kids',
      is_new: false,
      size: 'XS',
      color: 'blue, black, red,',
      in_stock: true,
      tags: 'best-seller',
      rating: 4,
    },
    {
      name: 'Chines Full Dress',
      description: 'Festive kids dress with comfy fit.',
      price: 34,
      image: '/images/pngegg (3).png',
      category: 'kids',
      is_new: true,
      size: 'XS, S',
      color: 'white, blue',
      in_stock: true,
      tags: 'new, jacket',
      rating: 4,
    },
    {
      name: 'Old Style Dress',
      description: 'Classic kids outfit with vintage charm.',
      price: 28,
      image: '/images/pngegg (4).png',
      category: 'kids',
      is_new: false,
      size: 'XS',
      color: 'blue, black, red, white',
      in_stock: true,
      tags: 'jacket',
      rating: 1,
    },
    {
      name: 'Zombie Style',
      description: 'Fun spooky set for kids parties.',
      price: 22,
      image: '/images/pngegg (5).png',
      category: 'kids',
      is_new: false,
      size: 'XS, S, M',
      color: 'red, white',
      in_stock: false,
      tags: 'short',
      rating: 0,
    },
    {
      name: 'Tiger Style',
      description: 'Cute tiger outfit, warm and comfy.',
      price: 26,
      image: '/images/pngegg (6).png',
      category: 'kids',
      is_new: false,
      size: 'S',
      color: 'white, red, gray',
      in_stock: true,
      tags: 'jacket, best-seller',
      rating: 4,
    },
  ]);
};