-- --- USER TABLE ---

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    email TEXT NOT NULL UNIQUE,

    password TEXT NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

--- --- INDEXES ---

CREATE INDEX IF NOT EXISTS idx_users_email
ON user (email);